// rasmlani import qvovomman
import home_img from "./assets/home.png";
import transport_img from "./assets/car.png";
import ish_img from "./assets/ish.png";
import xizmatlar_img from "./assets/xizmatlar.png";
import animals_img from "./assets/dog.png";
import toys_img from "./assets/toy.png";
import pc_img from "./assets/pc.png";
import cloth_img from "./assets/cloth.png";
import soft_img from "./assets/soft.png";
import travel_img from "./assets/travel.png";
import tekingaberaman_img from "./assets/tekinga-beraman.png";
import handshake_img from "./assets/handshake.png";

import cardImg from "./assets/test_card_img.jpg";

// images ...
const images = [
  { src: home_img, alt: "home image", name: "Ko'chmas mulk" },
  { src: transport_img, alt: "car image", name: "Transport" },
  { src: ish_img, alt: "bag image", name: "Ish" },
  {
    src: xizmatlar_img,
    alt: "the people with laptop image",
    name: "Xizmatlar",
  },
  { src: animals_img, alt: "dog image", name: "Hayvonlar" },
  { src: toys_img, alt: "toys image", name: "Bolalar dunyosi" },
  { src: pc_img, alt: "pc image", name: "Elektr jihozlari" },
  { src: cloth_img, alt: "cloth image", name: "Moda va stil" },
  { src: soft_img, alt: "soft image", name: "Uy va bog'" },
  { src: travel_img, alt: "sitcase image", name: "Xobbi, dam olish sport" },
  {
    src: tekingaberaman_img,
    alt: "black people😊 image",
    name: "Tekinga beraman",
  },
  { src: handshake_img, alt: "handshake image", name: "Ayirboshlash" },
];

// adressess ....
const addresses = [
  "O'zbekiston",
  "Toshkent Shahri",
  "Toshkent Viloyati",
  "Namangan",
  "Sirdaryo",
  "Jizzax",
  "Qashqadaryo",
  "Surxondaryo",
  "Navoiy",
  "Buxoro",
  "Xorazm",
  "Qoraqalpog'iston",
  "Samarqand",
  "Andijon",
  "Farg'ona",
];

// departments...
const departments = [
  { name: "Barchasi" },
  {
    name: "Ko'chmas mulk",
    categories: [
      "Kvartiralar",
      "Tijorat binolari",
      "Xususiy uylar",
      "Sutkalik ijarasi",
      "Yer uchastkasi",
      "Garajlar u002F turargohlar",
    ],
  },
  {
    name: "Transport",
    categories: [
      "Yengil avtomashinalar",
      "Yuk mashinalari",
      "Shinalar, Disklar, va g'ildiraklar",
      "Boshqa ehtiyot qisimlar",
      "Moto",
      "Avtobuslar",
      "Maxsus texnika",
      "Moto ehtiyot qisimlari va aksessuarlar",
      "Boshqa transport",
      "Suv transporti",
      "Qishloq xo'jalik texnikasi",
      "Avto ehtiyot qisimlari va aksessuarlar",
      "Tirkamalar",
      "Maxsus texnika uchun qisimlar",
    ],
  },
  {
    name: "Ish",
    categories: [
      "Turizm-dam-olish-oyinlar",
      "Go'zallik-fitnes-sport",
      "Chokanda savdo-sotuvlar",
      "Kotibiyat-Axo",
      "Madaniyat-san'at",
      "Karyerani boshlash, talabalar",
      "Barlar-restoranlar",
      "Transport-logistika",
      "Marketin-reklama-dizayn",
      "Qurilish",
      "Uy xodimlari",
      "Tibbiyor-formatsiya",
      "Ta'lim",
      "it-telekom-kompiyuterlar",
      "boshqa mash'gulotlar",
      "Ko'chmas mulk",
      "Qisman bandlik",
      "Ishlap chiqarish-energetika",
      "Yurisprudentsiya-va-buhgalteriya",
      "Qo'riqlash-xavfsizlik",
      "Xizmat ko'rsatish",
    ],
  },
  {
    name: "Xizmatlar",
    categories: [
      "Biznesni sotish",
      "Turizm",
      "Tarjimonlar xizmatlari-matnlarni terish",
      "Enagalar-kasalga qarovchilar",
      "Mahsulotlar prokati",
      "Qurilmalar",
      "Yuridik xizmatlar",
      "Hayvonlar uchun xizmatlar",
      "Xomashyo-materiallar",
      "Texnikaga xizmat ko'rsatish, ta'mirlash",
      "Avto-moto xizmatlar",
      "Avto-moto xizmatlar",
      "O'yinlar-san'at-foto-video",
      "Moliya xizmatlari",
      "Boshqa xizmatlar",
      "Qurilish-ta'mirlash-xona tozalash",
      "Go'zallik-salomatlik",
      "Ta'lim-sport",
      "Reklama, poligrafiya, marketing, internet",
    ],
  },
  {
    name: "Hayvonlar",
    categories: [
      "Itlar",
      "Topilmalar idorasi",
      "Kemiruvchilar",
      "Muhsuklar",
      "To'qish",
      "Akvarium baliqlar",
      "Boshqa hayvonlar",
      "Tekinga hayvonlar",
      "Qishloq xo'jalik hayvonlari",
      "Hayvonlar uchun mahsulotlar",
      "Qushlar",
    ],
  },
  {
    name: "Bolalar dunyosi",
    categories: [
      "Bolalar kolyaskalari",
      "Bolalar kiyimi",
      "Maktab o'quvchilari uchun mahsulotlar",
      "Bolalar mebeli",
      "Bolalar oyoq kiyimi",
      "Bolalar transporti",
      "Boshqa bolalar mahsulotlari",
      "O'yinchoqlar",
      "Bolalar avtoo'rindiqlari",
      "Oziqlantirish",
    ],
  },
  {
    name: "Elektr jihozlari",
    categories: [
      "Kompeyuterlar",
      "Telefonlar",
      "Uy uchun texnika",
      "Audiotexnika",
      "Telefonlar",
      "Yakka tartibdagi parvarish",
      "Tvu002F videotexnika",
      "O'yinlar va o'yin anjomlari",
      "Iqlim qurilmalari",
      "Fotou002F video",
      "Oziqlantirish",
      "Fotou002F video",
      "Aksessuarlar va komplekt jihozlar",
      "Boshqa elektronika",
    ],
  },
  {
    name: "Moda va stil",
    categories: [
      "Kiyim-kechak",
      "Qo'l soatlari",
      "Go'zallik-salomatlik",
      "Sovg'alar",
      "To'y uchun",
      "Moda, turli-tumanliklar",
      "Aksessuarlar",
    ],
  },
  {
    name: "Uy va bog'",
    categories: [
      "Xona o'simliklari",
      "Xo'jalik jihozlari, maishiy kimyo",
      "Jihozlar",
      "Mebel",
      "Bog' anjomlari",
      "Idish-tovoq, oshxona anjomlari",
      "Interyer jihozlari",
      "Kanstovarlar-chiqim materiallari",
      "Bog'-tomorqa",
      "Uy uchun boshqa mahsulotlar",
      "Qurilishu002Fta‘mirlash uchun tovarlar",
      "Oziq-ovqat u002F Ichimliklar",
    ],
  },
  {
    name: "Xobbi, dam olish sport",
    categories: [
      "Musiqa anjomlari",
      "Cd-dvd-plastinkalar, kassetalar",
      "Kitoblar-jurnallar",
      "Kitoblar-jurnallar",
      "Antikvar kolleksiyalar",
      "Boshqalar",
      "Chiptalar",
    ],
  },
  {
    name: "Tekinga beraman",
    categories: [],
  },
  {
    name: "Ayirboshlash",
    categories: [],
  },
];

// announcements...
let announcements = [
  {
    id: 1,
    name: "iphone 14 pro",
    description: "lorem ipsum dolar sit amet blabla",
    price: "800",
    price_type: "y.e.",
    category: "Elektr jihozlari",
    owner_phone_number: "339993399",
    form_of_sale: "Sotiladi",
    owner_address: "Tashkent",
    owner_district: "Yunusobod",
    img: cardImg,
    alt: "announcement image",
    date: "15-06-2024",
  },
  {
    id: 2,
    name: "iphone 15 pro",
    description: "lorem ipsum dolar sit amet blabla",
    price: "1200",
    price_type: "y.e.",
    category: "Elektr jihozlari",
    owner_phone_number: "339993399",
    form_of_sale: "Nasiya",
    owner_address: "Tashkent",
    owner_district: "Yunusobod",
    img: cardImg,
    alt: "announcement image",
    date: "15-06-2024",
  },
  {
    id: 3,
    name: "iphone 11 pro max",
    description: "lorem ipsum dolar sit amet blabla",
    price: "800000",
    price_type: "sum",
    category: "Elektr jihozlari",
    owner_phone_number: "339993399",
    form_of_sale: "Ayirboshlash",
    owner_address: "Buxoro",
    owner_district: "Yunusobod",
    img: cardImg,
    alt: "announcement image",
    date: "15-06-2024",
  },
  {
    id: 4,
    name: "iphone 11 pro max",
    description: "lorem ipsum dolar sit amet blabla",
    price: "800000",
    price_type: "sum",
    category: "Elektr jihozlari",
    owner_phone_number: "339993399",
    form_of_sale: "Ayirboshlash",
    owner_address: "Buxoro",
    owner_district: "Yunusobod",
    img: cardImg,
    alt: "announcement image",
    date: "15-06-2024",
  },
  {
    id: 4,
    name: "iphone 11 pro max",
    description: "lorem ipsum dolar sit amet blabla",
    price: "800000",
    price_type: "sum",
    category: "Elektr jihozlari",
    owner_phone_number: "339993399",
    form_of_sale: "Ayirboshlash",
    owner_address: "",
    owner_district: "Yunusobod",
    img: cardImg,
    alt: "announcement image",
    date: "",
  },
  {
    id: 4,
    name: "iphone 11 pro max",
    description: "lorem ipsum dolar sit amet blabla",
    price: "800000",
    price_type: "sum",
    category: "Elektr jihozlari",
    owner_phone_number: "339993399",
    form_of_sale: "Ayirboshlash",
    owner_address: "Buxoro",
    owner_district: "Yunusobod",
    img: cardImg,
    alt: "announcement image",
    date: "15-06-2024",
  },
];

// favorites
let favorites = [
  {
    id: 1,
    name: "iphone 14 pro",
    description: "lorem ipsum dolar sit amet blabla",
    price: "800",
    price_type: "y.e.",
    category: "Elektr jihozlari",
    owner_phone_number: "339993399",
    form_of_sale: "Sotiladi",
    owner_address: "Tashkent",
    owner_district: "Yunusobod",
    img: cardImg,
    alt: "announcement image",
    date: "15-06-2024",
  },
  {
    id: 2,
    name: "iphone 15 pro",
    description: "lorem ipsum dolar sit amet blabla",
    price: "1200",
    price_type: "y.e.",
    category: "Elektr jihozlari",
    owner_phone_number: "339993399",
    form_of_sale: "Nasiya",
    owner_address: "Tashkent",
    owner_district: "Yunusobod",
    img: cardImg,
    alt: "announcement image",
    date: "15-06-2024",
  },
  {
    id: 3,
    name: "iphone 11 pro max",
    description: "lorem ipsum dolar sit amet blabla",
    price: "800000",
    price_type: "sum",
    category: "Elektr jihozlari",
    owner_phone_number: "339993399",
    form_of_sale: "Ayirboshlash",
    owner_address: "Buxoro",
    owner_district: "Yunusobod",
    img: cardImg,
    alt: "announcement image",
    date: "15-06-2024",
  },
];

export { departments, announcements, images, addresses, favorites };
